apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: helm-qdrant
  annotations:
    meta.crossplane.io/maintainer: Hops Ops
    meta.crossplane.io/source: github.com/hops-ops/helm-qdrant
    meta.crossplane.io/description: Crossplane configuration for deploying Qdrant vector database via Helm.
spec:
  dependsOn:
  - provider: xpkg.crossplane.io/crossplane-contrib/provider-helm
    version: ">=v0.20.0"
  - function: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: ">=v0.6.0"
